### ISSUE TITLE
Getting english answers

### ISSUE THREAD

**Issue by mateusamorim96** [maritaca-ai/maritalk-api#3] opened 2023-07-27 19:17 UTC
Not sure why but after a few requests the API started replying me only in english, even if I explicit say that I want the answer in portuguese.

**Comment by rodrigo-f-nogueira** [comment] 2023-07-28 02:01
Hi @mateusamorim96, could you please provide an example so we can debug?

**Comment by marcelofprado** [comment] 2023-07-28 11:56
Also getting multiple answers in English today. 

> Prompt:  Quando a Formula 1 foi criada?
> Answer: I'm sorry, I don't understand what you're asking. Could you please rephrase or provide more information?

We are feeding search results as context for the answer to contain updated facts and they might include English websites.

**Comment by rodrigo-f-nogueira** [comment] 2023-07-28 22:51
In this case, since parts of the prompt are in English, you might need some prompt engineering. For example, I've added an instruction at the beginning explicitly asking to answer in Portuguese:

<img width="646" alt="Screen Shot 2023-07-29 at 6 47 57 AM" src="https://github.com/maritaca-ai/maritalk-api/assets/121117945/e7fd8734-d10c-44f0-a6a3-f07cb85c8f73">

**Comment by mateusamorim96** [comment] 2023-07-29 21:48
@rodrigo-f-nogueira one of my tries I asked that I wanted the answer in Portuguese but I still got english answer.

Message block:
`messages = [
    {"role": "user", "content": "Gostaria de sinônimos para a palavra 'caneta esferográfica' em português. Liste os exemplos em formato de lista Python."},
]`

Response I got:
Sure, here are some synonyms for "ballpoint pen" in Python list format:

* Ballpoint pen
* Biro
* Push-button pen
* Gel pen
* Rollerball pen
* Ink pen
* Permanent marker
* Fine-point pen
* Broad-tip pen
* Felt-tip pen
* Nib pen
* Quill pen
* Fountain pen
* Calligraphy pen
* Dip pen
* Stylus pen
* Fine-line pen
* Art pen
* Sketch pen
* Graphic pen
* Drawing pen
* Marker pen
* Highlighter pen
...
* Paper folding machine
* Paper binding machine
* Paper drilling machine
* Paper

**Comment by mateusamorim96** [comment] 2023-07-29 21:50
This behavior started after I submitted the same request a few times, I think after 3 or 4 tries it started to answer in English and providing wrong answers.

**Comment by rodrigo-f-nogueira** [comment] 2023-07-31 11:52
I was able to reproduce the same wrong answer:

<img width="602" alt="Screen Shot 2023-07-31 at 7 51 30 PM" src="https://github.com/maritaca-ai/maritalk-api/assets/121117945/8bdd44d9-26cc-4ce9-8522-2639d6dfef0c">

We will investigate. Thanks for letting us know.

**Comment by rodrigo-f-nogueira** [comment] 2024-03-14 17:38
Closing this due to the release of the new Sabiá-2, which is served under the MariTalk webchat. Please let us know if the problem persists!

**Closed by rodrigo-f-nogueira** 2024-03-14 17:38 UTC
